ALTER TABLE games ADD COLUMN IF NOT EXISTS time_control_seconds INTEGER;
ALTER TABLE games ADD COLUMN IF NOT EXISTS white_ms_remaining INTEGER;
ALTER TABLE games ADD COLUMN IF NOT EXISTS black_ms_remaining INTEGER;
ALTER TABLE games ADD COLUMN IF NOT EXISTS turn_started_at TIMESTAMPTZ;
